### PR TITLE
correct the variable in Literal example

### PR DESCRIPTION
**Pull request by Mearman**

### CODE REVIEW

**Comment by angrykoala** [comment]
Good catch!

**Comment by angrykoala** [comment]
Hi @Mearman 
In order to merge this PR, we need you to sign the Neo4j CLA. You have more information, document, and steps to sign here: https://neo4j.com/developer/cla/

If you agree to it, please let me know when you have signed 🙂

(The automated message from before is still a work in progress)

**Comment by Mearman** [comment]
Done :)

**Comment by angrykoala** [comment]
Thanks @Mearman

**Pull request merged**
